- name: Configure Frontend Server
  hosts: frontend
  become: true
  tasks:
    - name: Install nginx
      ansible.builtin.dnf:
        name: nginx
        state: installed

    - name: Start and Enable nginx service
      ansible.builtin.service:
        name: nginx
        state: reloaded
        enabled: true

    - name: Delete existing html directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: absent

    - name: Create html directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: directory

    - name: Extract frontend code # Download and extract can be here
      ansible.builtin.unarchive:
        src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
        dest: /usr/share/nginx/html/
        remote_src: true

    - name: Copy expense configuration code
      ansible.builtin.copy:
        src: expense.conf
        dest: /etc/nginx/default.d/expense.conf

    - name: Restart nginx service
      ansible.builtin.service:
        name: nginx
        state: restarted
